public enum TriggerType
{
    OnBattleStart,
    OnBattleEnd,
    OnTurnStart,
    OnTurnEnd,
    OnNegativeStatusApplied,
    OnPositiveStatusApplied,
    OnDamage,
    OnHealthDamage,
    OnDamageShielded,
    OnShieldBroken,
    OnShieldGiven,
    OnHeal,
    OnDeath,
    OnMove,
    OnStrike,
    OnApply,
    OnEnergyRestore,
    OnEnergyDrain
}
